# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CMPE188-Jupyter',
                'doc_host': 'https://klam20.github.io',
                'git_url': 'https://github.com/klam20/CMPE188-Jupyter',
                'lib_path': 'CMPE188_Jupyter'},
  'syms': {'CMPE188_Jupyter.core': {'CMPE188_Jupyter.core.foo': ('core.html#foo', 'CMPE188_Jupyter/core.py')}}}
